// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL4wVGgMRFE4-Iv6FBBDsHfgyRu5e4kp4',
    appId: '1:923130072556:web:df81207d465f5051b6c4c9',
    messagingSenderId: '923130072556',
    projectId: 'swap-fyp1620',
    authDomain: 'swap-fyp1620.firebaseapp.com',
    databaseURL: 'https://swap-fyp1620-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swap-fyp1620.firebasestorage.app',
    measurementId: 'G-QC4R9Z47K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9I0Y8vbrD-wRGy6iAH0M5kr7RRS2BA7M',
    appId: '1:923130072556:android:6bbf435a37cf3c07b6c4c9',
    messagingSenderId: '923130072556',
    projectId: 'swap-fyp1620',
    databaseURL: 'https://swap-fyp1620-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swap-fyp1620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbqmYUgix9Nj9r0kQPYJpjqXbWUvwu5k',
    appId: '1:923130072556:ios:0ff1ec573d078444b6c4c9',
    messagingSenderId: '923130072556',
    projectId: 'swap-fyp1620',
    databaseURL: 'https://swap-fyp1620-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swap-fyp1620.firebasestorage.app',
    iosBundleId: 'com.example.swap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbqmYUgix9Nj9r0kQPYJpjqXbWUvwu5k',
    appId: '1:923130072556:ios:0ff1ec573d078444b6c4c9',
    messagingSenderId: '923130072556',
    projectId: 'swap-fyp1620',
    databaseURL: 'https://swap-fyp1620-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swap-fyp1620.firebasestorage.app',
    iosBundleId: 'com.example.swap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL4wVGgMRFE4-Iv6FBBDsHfgyRu5e4kp4',
    appId: '1:923130072556:web:f509e3bf9b20bf2ab6c4c9',
    messagingSenderId: '923130072556',
    projectId: 'swap-fyp1620',
    authDomain: 'swap-fyp1620.firebaseapp.com',
    databaseURL: 'https://swap-fyp1620-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swap-fyp1620.firebasestorage.app',
    measurementId: 'G-CGRXKW8X8S',
  );
}
